### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by apryamostanov** [INFINITE-TECHNOLOGY/SUPPLIES#3]
2019-12-25 00:19:31:560|error|main|io.infinite.pigeon.App|java.lang.NullPointerException
	at io.infinite.supplies.ast.exceptions.ExceptionUtils.stacktrace(ExceptionUtils.groovy:11)
	at BobbinScriptEngineImpl.formatLineThrowable(script1577218765361577288688.groovy:40)
	at io.infinite.bobbin.destinations.Destination.logThrowable(Destination.groovy:50)
	at io.infinite.bobbin.Bobbin$_logThrowable_closure5.doCall(Bobbin.groovy:67)
	at io.infinite.bobbin.Bobbin$_logThrowable_closure5.call(Bobbin.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2322)
	at io.infinite.bobbin.Bobbin.logThrowable(Bobbin.groovy:66)
	at io.infinite.bobbin.Bobbin.info(Bobbin.groovy:159)
	at org.slf4j.bridge.SLF4JBridgeHandler.callPlainSLF4JLogger(SLF4JBridgeHandler.java:232)
	at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:305)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.info(Logger.java:1490)
	at io.infinite.pigeon.App.runWithLogging(App.groovy:61)
	at io.infinite.pigeon.App.run(App.groovy:52)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at io.infinite.pigeon.App.main(App.groovy:47)

**Comment by apryamostanov** [comment]
Fixed in 1.1.10
